version: "3"
services:
  bas-dev:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    network_mode: "host"
    volumes:
      - ./:/workspace
    command: /bin/sh -c "cd /home/bas && jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser"
